# Generated by Django 4.1.1 on 2022-09-24 11:06

import django.contrib.auth.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        
    ]

    operations = [
        migrations.CreateModel(
            name='LoginUser',
            fields=[
                ('username', models.CharField(blank=True, max_length=20, unique=True)),
                ('orname', models.CharField(blank=True, max_length=50)),
                ('ortype', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=50)),
                ('password', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'db_table': 'user',
            },
            
        ),
    ]
